import Head from 'next/head'
import Image from 'next/image'
import Page from '../components/design-library/Page';
import VerticalSpacing, { VerticalSpacingSize } from '../components/design-library/VerticalSpacing';
import Heading from '../components/design-library/Heading';
import SubHeading from '../components/design-library/SubHeading';
import FilterBar from '../components/FilterBar/FilterBar';
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Nova Search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        <VerticalSpacing>
          <VerticalSpacing size={VerticalSpacingSize.SMALL}>
            <Heading>Transactions</Heading>
            <SubHeading>Your business contracts, including fund subscriptions or applications.</SubHeading>
          </VerticalSpacing>
          <FilterBar />
        </VerticalSpacing>
      </Page>
    </>
  )
}
