import Head from 'next/head'
import Page from '../components/design-library/Page';
import Transactions from '../components/Transactions';
import ClientOnly from '../components/ClientOnly';

export default function Home() {
  return (
    <>
      <Head>
        <title>Nova Search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ClientOnly className="h-full">
        <Page>
          <Transactions />
        </Page>
      </ClientOnly>
    </>
  )
}
